Repository yanaagi/cs-expo-2023, pull requests merged in 2023-11, with the labels that each got.

#109 feat: ADD 4 circular buttons with working view event detail links
  cs-expo-2023/app/events/page.tsx
  cs-expo-2023/components/EventsOverviewHeader.tsx
Labels: enhancement

#114 feat: FIX alternating layout
  cs-expo-2023/app/partners/page.tsx
  cs-expo-2023/app/projects/collections-of-projects/page.tsx
  cs-expo-2023/components/AlternatingPartnersLayout.tsx
  cs-expo-2023/components/PartnersSidebar.tsx
  cs-expo-2023/components/ProjectsSidebar.tsx
Labels: enhancement, In Progress

#115 feat: EDIT contents of json
  cs-expo-2023/partners.json
Labels: enhancement, Done

#113 fix: smooth transition of carousel & responsiveness - Projects Overview
  cs-expo-2023/app/projects/page.tsx
  cs-expo-2023/components/ProjectsCarousel.tsx
  cs-expo-2023/components/ProjectsHeader.tsx
Labels: enhancement

#118 feat: ADD json file for speaker and panelist, and MODIFY page.tsx of …
  cs-expo-2023/app/events/cs-expo/page.tsx
  cs-expo-2023/app/events/dev-day/page.tsx
  cs-expo-2023/components/SpeakerPanelistLayout.tsx
  cs-expo-2023/panelists.json
  cs-expo-2023/speakers.json
Labels: enhancement, dependencies, Done

#120 docs: FIX project structure
  README.md
Labels: documentation, In Progress

#119 Footer
  cs-expo-2023/app/events/cs-expo/page.tsx
  cs-expo-2023/app/events/dev-day/page.tsx
  cs-expo-2023/app/partners/page.tsx
  cs-expo-2023/components/Footer.tsx
Labels: enhancement

#111 CHANGE Committee square sizes now adjusts when the window is being re…
  cs-expo-2023/app/events/committees/page.tsx
  cs-expo-2023/components/CommitteesGrid.tsx
  cs-expo-2023/components/CommitteesPic.tsx
Labels: enhancement

#116 feat & fix: add filter functionality to sidebar AND fix collection of projects header responsiveness
  cs-expo-2023/app/projects/collections-of-projects/page.tsx
  cs-expo-2023/components/CollectionOfProjectsHeader.tsx
  cs-expo-2023/components/GroupCardLayout.tsx
  cs-expo-2023/components/ProjectsSidebar.tsx
Labels: enhancement

#130 fix: footer.tsx
  cs-expo-2023/components/Footer.tsx
  cs-expo-2023/tailwind.config.ts
Labels: enhancement

#126 Add responsiveness
  cs-expo-2023/app/globals.css
  cs-expo-2023/app/layout.tsx
  cs-expo-2023/app/projects/hall-of-fame/page.tsx
  cs-expo-2023/components/HallOfFameCarousel.tsx
Labels: enhancement, Done

#133 REFACTOR: NavBar.tsx Responsiveness
  cs-expo-2023/components/NavBar.tsx
Labels: enhancement

#134 feat: AboutComponent Photo resize, add new line on dev-day speakers p…
  cs-expo-2023/app/events/dev-day/page.tsx
  cs-expo-2023/components/AboutComponent.tsx
Labels: enhancement

#137 REFACTOR: Footer.tsx Responsiveness
  cs-expo-2023/components/Footer.tsx
Labels: enhancement

#141 feat: ADD sidebar toggle for mobile and on-hover on desktops
  cs-expo-2023/components/GroupCardLayout.tsx
  cs-expo-2023/components/ProjectsSidebar.tsx
Labels: enhancement, Done

#138 fix: UPDATE responsiveness for partners page
  cs-expo-2023/app/partners/page.tsx
Labels: enhancement

#140 REFACTOR: Footer.tsx
  cs-expo-2023/components/Footer.tsx
Labels: enhancement

#107 Homepagev2
  cs-expo-2023/app/events/page.tsx
  cs-expo-2023/app/page.tsx
  cs-expo-2023/components/EventsOverviewHeader.tsx
  cs-expo-2023/components/HomeOverviewHeader.tsx
Labels: enhancement

#135 CHANGE the squares and header are now responsive and the squares have…
  cs-expo-2023/app/events/committees/page.tsx
  cs-expo-2023/components/CommitteesGrid.tsx
  cs-expo-2023/components/CommitteesPic.tsx
  cs-expo-2023/components/MeetTheCommitteesHeader.tsx
Labels: enhancement

#139 REFACTOR: NavBar.tsx
  cs-expo-2023/components/NavBar.tsx
Labels: enhancement

#129 feat: FIX responsiveness of text when on smaller screens
  cs-expo-2023/app/events/page.tsx
  cs-expo-2023/app/partners/page.tsx
  cs-expo-2023/components/EventsOverviewHeader.tsx
  cs-expo-2023/tailwind.config.ts
Labels: enhancement, Done

#157 REFACTOR favicon.ico
  cs-expo-2023/app/favicon.ico
Labels: enhancement

#158 feat: FIX description responsiveness
  cs-expo-2023/app/events/page.tsx
  cs-expo-2023/components/EventsOverviewHeader.tsx
Labels: enhancement, Done

#159 fix picture
  cs-expo-2023/app/events/committees/page.tsx
  cs-expo-2023/components/CommitteesPic.tsx
Labels: In Progress

#173 fix: UPDATE NavBar.tsx
  cs-expo-2023/components/NavBar.tsx
  cs-expo-2023/public/cs-expo-logo-black.png
  cs-expo-2023/public/cs-expo-logo-white.png
Labels: enhancement

#176 fix: Footer cs logo
  cs-expo-2023/components/Footer.tsx
Labels: enhancement

#182 UPDATE partners logos
  cs-expo-2023/app/page.tsx
  cs-expo-2023/components/HomeOverviewHeader.tsx
  cs-expo-2023/package-lock.json
  cs-expo-2023/package.json
  cs-expo-2023/public/acomms-logo.jpg
  cs-expo-2023/public/bu-access-logo.jpg
  cs-expo-2023/public/cgi-logo.png
  cs-expo-2023/public/compile-logo.jpg
  cs-expo-2023/public/comssa-logo.jpg
  cs-expo-2023/public/cs-pup-logo.jpg
  cs-expo-2023/public/csa-logo.jpg
  cs-expo-2023/public/csso-logo.jpg
  cs-expo-2023/public/cvsu-sites-logo.jpg
  cs-expo-2023/public/diyaryo-milenyo-logo.jpg
  cs-expo-2023/public/gadgets-mag-logo.jpg
  cs-expo-2023/public/icpep-plm-logo.jpg
  cs-expo-2023/public/iecep-musc-logo.jpg
  cs-expo-2023/public/journal-ol-logo.jpg
  cs-expo-2023/public/jpcs-apc-logo.jpg
  cs-expo-2023/public/kooapps-logo.png
  cs-expo-2023/public/pldt-smart-logo.png
  cs-expo-2023/public/pointwest-logo.png
  cs-expo-2023/public/pup-guild-logo.jpg
  cs-expo-2023/public/pupascii-logo.jpg
  cs-expo-2023/public/qube-logo.png
  cs-expo-2023/public/tech-acm-logo.jpg
  cs-expo-2023/public/uas-logo.png
  cs-expo-2023/yarn.lock
Labels: In Progress

#187 feat: frame color change
  cs-expo-2023/app/events/committees/page.tsx
  cs-expo-2023/app/page.tsx
  cs-expo-2023/components/HomeOverviewHeader.tsx
  cs-expo-2023/components/NavBar.tsx
  cs-expo-2023/package-lock.json
  cs-expo-2023/package.json
  cs-expo-2023/public/acomms-logo.jpg
  cs-expo-2023/public/bu-access-logo.jpg
  cs-expo-2023/public/cgi-logo.png
  cs-expo-2023/public/compile-logo.jpg
  cs-expo-2023/public/comssa-logo.jpg
  cs-expo-2023/public/cs-pup-logo.jpg
  cs-expo-2023/public/csa-logo.jpg
  cs-expo-2023/public/csso-logo.jpg
  cs-expo-2023/public/cvsu-sites-logo.jpg
  cs-expo-2023/public/diyaryo-milenyo-logo.jpg
  cs-expo-2023/public/gadgets-mag-logo.jpg
  cs-expo-2023/public/icpep-plm-logo.jpg
  cs-expo-2023/public/iecep-musc-logo.jpg
  cs-expo-2023/public/journal-ol-logo.jpg
  cs-expo-2023/public/jpcs-apc-logo.jpg
  cs-expo-2023/public/kooapps-logo.png
  cs-expo-2023/public/pldt-smart-logo.png
  cs-expo-2023/public/pointwest-logo.png
  cs-expo-2023/public/pup-guild-logo.jpg
  cs-expo-2023/public/pupascii-logo.jpg
  cs-expo-2023/public/qube-logo.png
  cs-expo-2023/public/tech-acm-logo.jpg
  cs-expo-2023/public/uas-logo.png
  cs-expo-2023/yarn.lock
Labels: In Progress
