Repository yanaagi/cs-expo-2023, pull requests merged in 2023-10, with the labels that each got.

#1 Back end events/home
  cs-expo-2023/app/events/committees/index.tsx
  cs-expo-2023/app/events/committees/page.tsx
  cs-expo-2023/app/events/cs-expo/index.tsx
  cs-expo-2023/app/events/cs-expo/page.tsx
  cs-expo-2023/app/events/dev-day/index.tsx
  cs-expo-2023/app/events/dev-day/page.tsx
  cs-expo-2023/app/home/index.tsx
  cs-expo-2023/app/home/page.tsx
  cs-expo-2023/yarn.lock
  node_modules/.yarn-integrity
  yarn.lock
Labels: good first issue

#27 docs: WRITE early version of README
  README.md
Labels: documentation, In Progress

#40 feat: ADD the component PartnersHeader.tsx and ThesisPosterCard.tsx
  cs-expo-2023/app/projects/page.tsx
  cs-expo-2023/components/PartnersHeader.tsx
  cs-expo-2023/components/ThesisPosterCard.tsx
Labels: dependencies

#41 fix: UPDATE the PartnersHeader.tsx
  cs-expo-2023/components/PartnersHeader.tsx
Labels: bug

#38 docs: ADD a Table of Contents for README file
  README.md
Labels: documentation, In Progress

#47 fix: UPDATE ProjectsHeader.tsx and page.tsx
  cs-expo-2023/app/projects/page.tsx
  cs-expo-2023/components/PartnersHeader.tsx
  cs-expo-2023/components/ProjectsHeader.tsx
Labels: dependencies, In Progress

#50 feat: Edited Events Overview page and added component
  cs-expo-2023/app/events/page.tsx
  cs-expo-2023/components/EventsOverviewHeader.tsx
Labels: dependencies, In Progress

#52 51 partners page
  .gitignore
  cs-expo-2023/app/partners/page.tsx
  cs-expo-2023/components/AlternatingPartnersLayout.tsx
  cs-expo-2023/components/PartnersItemLayout.tsx
  cs-expo-2023/components/PartnersLeftLayout.tsx
  cs-expo-2023/components/PartnersRightLayout.tsx
  cs-expo-2023/partners.json
Labels: dependencies

#53 refactor: COMBINE AlternatingPartnersLayout, PartnersLeftLayout, and …
  cs-expo-2023/app/partners/page.tsx
  cs-expo-2023/components/AlternatingPartnersLayout.tsx
  cs-expo-2023/components/PartnersItemLayout.tsx
  cs-expo-2023/components/PartnersLeftLayout.tsx
  cs-expo-2023/components/PartnersRightLayout.tsx
  cs-expo-2023/partners.json
Labels: enhancement

#59 feat: ADD AboutComponent, ButtonComponent, PhotoComponent, CHANGE in …
  cs-expo-2023/app/events/cs-expo/page.tsx
  cs-expo-2023/components/AboutComponent.tsx
  cs-expo-2023/components/ButtonComponent.tsx
  cs-expo-2023/components/PhotoComponent.tsx
Labels: dependencies

#68 FIX two footers in homepage
  cs-expo-2023/app/page.tsx
Labels: bug

#69 docs: ADD warnings again about the use of git pull origin main
  README.md
Labels: documentation

#71 fix: UPDATE NavBar.tsx
  cs-expo-2023/components/NavBar.tsx
Labels: bug

#65 made a function that will read the thesis-projects.json
  cs-expo-2023/app/projects/collections-of-projects/page.tsx
  cs-expo-2023/components/ThesisProjectReader.tsx
  cs-expo-2023/package-lock.json
  cs-expo-2023/package.json
  cs-expo-2023/thesis-projects.json
  cs-expo-2023/yarn.lock
Labels: enhancement

#60 feat: CHANGE dev day page.tsx
  cs-expo-2023/app/events/dev-day/page.tsx
Labels: dependencies

#74 fix: remove unecessary code of lines at 17 and 220
  cs-expo-2023/app/events/cs-expo/page.tsx
Labels: bug

#73 FIX cannot use npm run dev command in terminal
  cs-expo-2023/package-lock.json
  cs-expo-2023/package.json
  cs-expo-2023/yarn.lock
  package-lock.json
  package.json
  yarn.lock
Labels: bug, In Progress

#75 fix: MODIFY dev-day/page.tsx errors
  cs-expo-2023/app/events/dev-day/page.tsx
Labels: bug

#77 fix: MODIFY footer component to load logo
  cs-expo-2023/components/Footer.tsx
Labels: bug

#78 fix: UPDATE website name
  cs-expo-2023/app/layout.tsx
Labels: Done

#105 docs:FIX table of contents. ADD a file tree.
  README.md
Labels: documentation, In Progress

#106 ADD the meet the committees and learn more is clickable
  cs-expo-2023/app/events/committees/page.tsx
  cs-expo-2023/components/CommitteesGrid.tsx
  cs-expo-2023/components/MeetTheCommitteesHeader.tsx
  cs-expo-2023/yarn.lock
Labels: enhancement
